services:
  search-service:
    build: .
    container_name: search-service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    networks:
      - devops-network
    environment:
      SECRET_KEY: super-secret-accommodation-key
      JWT_SIGNING_KEY: shared-jwt-secret
      ACCOMMODATION_URL: "http://accommodations-service:8000/api/accommodations/"
      PYTHONUNBUFFERED: 1

networks:
  devops-network:
    driver: bridge