services:
  search-service:
    build: .
    container_name: search-service
    env_file:
      - .env
    command: >
      sh -c "
      sh scripts/wait-for-service.sh accommodations-db 5432 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - devops

networks:
  devops:
    name: devops-network
    driver: bridge
